# **Numpy Operatoins**

In [1]:
# creatae an array of 4x4 zeros
import numpy as np
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [2]:
# create an array with constant value

np.full((4,4),11,dtype=float)

array([[11., 11., 11., 11.],
       [11., 11., 11., 11.],
       [11., 11., 11., 11.],
       [11., 11., 11., 11.]])

In [4]:
# create a numpy array of 4x4 with diagonal elements as True and Non diagonal elements as False

In [5]:
np.identity(5)  # Square matrix- 2D-->[[ ]]

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
# in pthon except 0 '' None[] () everything is True

np.identity(5,dtype=bool)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

In [7]:
bool(234)

True

In [8]:
# create a numpy array of 4x4 with diagonal elements as false and Non diagonal elements as True

~np.identity(5,dtype=bool)

array([[False,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True, False,  True],
       [ True,  True,  True,  True, False]])

In [9]:
# acess diagonal elements of numpy array
s= np.identity(5)
s.diagonal()

array([1., 1., 1., 1., 1.])

# **Numpy Slicing and Indexing**

In [11]:
x = np.arange(24).reshape(6,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
x[3] # using index we can access one row at a time

array([12, 13, 14, 15])

In [14]:
print(x[3][3])  # row with elements index

15


In [15]:
x[3,3]

np.int64(15)

In [16]:
# numpy array is mutable in nature
x[3,3]

np.int64(15)

In [18]:
# replace 15 by 50
x[3,3] = 50
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 50],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [19]:
# acess more rows
x[1:4]  # [start_index:stop_index]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 50]])

In [20]:
# acess last 3 rows
# x[-3]  # -ve index
x[3:]  # +ve index

array([[12, 13, 14, 50],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [21]:
x [::-2]  # stepping

array([[20, 21, 22, 23],
       [12, 13, 14, 50],
       [ 4,  5,  6,  7]])

In [23]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 50],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [24]:
# column operation

x[-2:,-2:]  # [row,column]

array([[18, 19],
       [22, 23]])

In [25]:
x[-2:,-2]

array([18, 22])

In [26]:
x [2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [27]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 50],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [28]:
#[8,11][12,50]
x[2:4,::3]

array([[ 8, 11],
       [12, 50]])