# **Numpy**

In [27]:
import numpy as np

In [28]:
# 1

a=np.array([20,10,99,30,1000])

a


array([  20,   10,   99,   30, 1000])

In [29]:
np

<module 'numpy' from '/usr/local/lib/python3.12/dist-packages/numpy/__init__.py'>

In [30]:
np.__version__

'2.0.2'

In [31]:
a

array([  20,   10,   99,   30, 1000])

In [32]:
# find max number
print(a.max())

1000


In [33]:
a.min()

np.int64(10)

In [34]:
# how many elements present
a.size

5

In [35]:
# dimension
a.ndim

1

In [36]:
type(a)

numpy.ndarray

In [37]:
# Q. Whart is a type of Numpy array?

In [38]:

b = np.array([[10,20,1],
              [-1,5,9],
              [7,40,2]])

b

array([[10, 20,  1],
       [-1,  5,  9],
       [ 7, 40,  2]])

In [39]:
b.ndim

2

In [40]:
# to chenk number of row

b.shape  # (rows,column)

(3, 3)

In [41]:
# additon of all elements

print(b.sum())

93


In [42]:
b

array([[10, 20,  1],
       [-1,  5,  9],
       [ 7, 40,  2]])

In [43]:
# columnwise additon
print(b.sum(axis=0))

[16 65 12]


In [44]:
# Assignment: b.min(), b.max(), b.mean(),b.std()

print(b.min())

print(b.min(axis=0))

-1
[-1  5  1]


In [45]:
print(b.max())

print(b.max(axis=0))

40
[10 40  9]


In [46]:
print(b.mean())

print(b.mean(axis=0))

10.333333333333334
[ 5.33333333 21.66666667  4.        ]


In [56]:
a.ndim

1

In [47]:
print(b.std())

print(b.std(axis=0))

12.01850425154663
[ 4.64279609 14.33720878  3.55902608]


In [57]:
b.ndim

2

In [58]:
a.ndim

1

In [59]:
a

array([  20,   10,   99,   30, 1000])

In [60]:
b

array([[10, 20,  1],
       [-1,  5,  9],
       [ 7, 40,  2]])

In [49]:
b.__getitem__(-1)

array([ 7, 40,  2])

# Different ways to creating numpy arrays

In [50]:
# numpy aray with random numbers
np.random.random(5)

array([0.26305741, 0.14704555, 0.94858217, 0.64707097, 0.52807268])

In [51]:
np.random.random((5,4))

array([[0.31077617, 0.31162632, 0.10672011, 0.96614999],
       [0.77232276, 0.04663661, 0.4644381 , 0.93992031],
       [0.79887813, 0.96896194, 0.15830984, 0.52135139],
       [0.96532878, 0.61074298, 0.33415241, 0.23303424],
       [0.17953894, 0.65835236, 0.57018333, 0.23564526]])

In [61]:
# 3D (block,row,column)
np.random.random((2,2,2,))

array([[[0.90531354, 0.0645691 ],
        [0.00256824, 0.0472007 ]],

       [[0.53194842, 0.175535  ],
        [0.91398285, 0.98052209]]])

In [53]:
help(np.random.random)

Help on method random in module numpy.random.mtrand:

random(size=None) method of numpy.random.mtrand.RandomState instance
    random(size=None)

    Return random floats in the half-open interval [0.0, 1.0). Alias for
    `random_sample` to ease forward-porting to the new random API.



In [62]:
np.random

<module 'numpy.random' from '/usr/local/lib/python3.12/dist-packages/numpy/random/__init__.py'>

In [63]:
# generate array with sequence of numbers

c = np.arange(24)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

c.size

In [66]:
# Convert from 1D to 2D
# Use reshape()--> TEMP
# 6x4,8x3,12x2,1x24
c.reshape((6,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [67]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [69]:
# resize() used for parmnt. changes in dimension
c.resize((3,8))

In [70]:
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [71]:
c.shape

(3, 8)

In [72]:
# convert nD to 1D--> use ravel()--> TEMP
c.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [73]:
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])